name: Build Frontier Analytics image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        env:
          cern_user: ${{ secrets.CERN_USER }}
          cern_pass: ${{ secrets.CERN_PASS }}
        with:
          image: atlasanalyticsservice/frontier
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: "CERN_USER=${{ secrets.CERN_USER }},CERN_PASS=${{ secrets.CERN_PASS }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FRONTIER_DEPLOYMENT_TOKEN }}
          repository: ATLAS-Analytics/Frontier-deployment
          event-type: gitops-frontier-app-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
